# Generated by Django 4.2.1 on 2023-09-14 08:13

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('mobile_number', api.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, region=None, unique=True)),
                ('pan', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('otp', models.CharField(blank=True, max_length=256, null=True)),
                ('validity', models.DateTimeField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=True)),
                ('order_complete', models.BooleanField(default=False)),
                ('referral_id', models.CharField(blank=True, max_length=250, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=100, null=True, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_transaction', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('invoice_number', models.CharField(help_text="Invoice number starting with 'M' and 8 digits.", max_length=20, null=True, unique=True)),
                ('delivered_on', models.DateField(blank=True, help_text='Date when the order was delivered.', null=True)),
                ('delivery_partner', models.CharField(blank=True, help_text="Delivery partner's name.", max_length=255, null=True)),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryRewardPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.CharField(blank=True, max_length=100, null=True)),
                ('new_user', models.CharField(blank=True, max_length=100, null=True)),
                ('matching_count', models.IntegerField(blank=True, null=True)),
                ('PRP_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpotRewardPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('referral', models.CharField(blank=True, max_length=100, null=True)),
                ('eligible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryRewardPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('referred_su1', models.CharField(blank=True, max_length=100, null=True)),
                ('referred_su2', models.CharField(blank=True, max_length=100, null=True)),
                ('reward_category', models.CharField(choices=[('first_join', 'first_join'), ('first_reward', 'first_reward')], max_length=100)),
                ('PRP_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.primaryrewardpoint')),
                ('eligible_su', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_su', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('claimed', 'claimed'), ('skipped', 'skipped'), ('delivered', 'delivered')], max_length=20, null=True)),
                ('claimed_on', models.DateTimeField(blank=True, null=True)),
                ('criteria', models.CharField(blank=True, choices=[('RPC1', 'RPC1'), ('RPC2', 'RPC2'), ('RPC3', 'RPC3'), ('RPC4', 'RPC4')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_claim_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.IntegerField()),
                ('sales_considered', models.IntegerField()),
                ('sales_carry_forwarded', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PRPMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_user1', models.CharField(blank=True, max_length=100, null=True)),
                ('matching_user2', models.CharField(blank=True, max_length=100, null=True)),
                ('PRP_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.primaryrewardpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('prp_team_count', models.IntegerField()),
                ('primary_rp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('secondary_rp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referral_count', models.IntegerField()),
                ('spot_rp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repurchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('item_line_no', models.AutoField(primary_key=True, serialize=False)),
                ('product_group', models.CharField(default='Garments', max_length=255)),
                ('product_category', models.CharField(default='T-shirts', max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='KYCImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('proof_type', models.CharField(choices=[('ID1', 'ID1'), ('ID2', 'ID2')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('account_type', models.CharField(max_length=50)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
