# Generated by Django 4.2.1 on 2023-09-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_delivered_on_order_delivery_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(help_text="Invoice number starting with 'M' and 8 digits.", max_length=20, null=True, unique=True),
        ),
    ]
