# Generated by Django 4.2.1 on 2023-09-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='decimal_value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
